# This file was generated by GoReleaser. DO NOT EDIT.
cask "poit" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "76ae7a35cb7ef079b0b86caf2cceefecae0e32d57fb2f3e534399062ceb1c576"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1109d0813ae5d3bde96d6603362b461813c45198eb88b25a93af8601d72e947"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eff85d445ed539e21375ed83827131d53efb45ba65981da8afa9b618eaf7e89e"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "831df46e6d2be382969741c2136e720bbb330b3211ff9de7bf4a50c842893853"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poit"
  desc ""
  homepage "https://github.com/rowicy/poit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poit"]
    end
  end

  # No zap stanza required
end
