# This file was generated by GoReleaser. DO NOT EDIT.
cask "poit" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "243617135da92d87eb6fa24dcf5e7d4c375b8aaa6a79e512c56ca8413b554ec8"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62b52e14c5fed039c5d910542cc99a03fb2523d5d3f9422451c11d06ef600ec9"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f1f36e16491a353ae0cbfb5415d064e0b83ccf3fe6c13f15816e85dd4f97e402"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b1ff2c0a09671598231563d5dac1168a168b4bbe4dbd776f60b77e2e36772019"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poit"
  desc ""
  homepage "https://github.com/rowicy/poit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poit"

  # No zap stanza required
end
