# This file was generated by GoReleaser. DO NOT EDIT.
cask "poit" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "eb6a0b726628ec0d45b99c49cca27faac90ac6636e2ef4a0690a3b3126280aab"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5c98af23e0c60e3eccedc2c239a9add70843a61a5c26afcb02d4b1b6b983e6b"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d96871cc08df4f7f7913fc737bef1ef777cf23921d8cf37a6458c19f4636bde5"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d3b086641cb13c112cc68faf5a7f2db585ecdcb90698066035a3a0e5e55c8075"
      url "https://github.com/rowicy/poit/releases/download/v#{version}/poit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poit"
  desc ""
  homepage "https://github.com/rowicy/poit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poit"]
    end
  end

  # No zap stanza required
end
